[package]
name = "lem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terrain_graph = { git = "https://github.com/TadaTeruki/terrain-graph", version = "0.2" }
delaunator = "1.0"
voronoice = "0.2"

[dev-dependencies]
terrain_visualizer = { git = "https://github.com/TadaTeruki/terrain-visualizer" }
rand = "0.8"
image = "0.24"