[package]
name = "fastlem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtree_rs = "0.1"
voronoice = "0.2"
terrain-graph = "1.0"
naturalneighbor = { git = "https://github.com/TadaTeruki/naturalneighbor" }

[dev-dependencies]
rand = "0.8"
image = "0.24"
noise = {version = "0.8.2", features = ["images"]}
terrain_visualizer = { git = "https://github.com/TadaTeruki/terrain-visualizer" }
