use crate::core::{traits::Site, units::Altitude};

/// Represents a terrain generated by `TerrainGenerator`.
/// ### Properties
/// - `sites` is the set of sites.
/// - `altitudes` is the set of altitudes.
#[derive(Default)]
pub struct Terrain<S: Site> {
    pub sites: Vec<S>,
    pub altitudes: Vec<Altitude>,
}

impl<S: Site> Terrain<S> {
    pub fn new(sites: Vec<S>, altitudes: Vec<Altitude>) -> Self {
        Self { sites, altitudes }
    }
}
