use crate::units::{Altitude, Site};

/// Represents a terrain generated by `TerrainGenerator`.
/// ### Properties
/// - `sites` is the set of sites.
/// - `altitudes` is the set of altitudes.
#[derive(Default)]
pub struct Terrain {
    pub sites: Vec<Site>,
    pub altitudes: Vec<Altitude>,
}

impl Terrain {
    pub fn new(sites: Vec<Site>, altitudes: Vec<Altitude>) -> Self {
        Self { sites, altitudes }
    }
}
